apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperless-route
  namespace: paperless
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-issuer
spec:
  ingressClassName: kong
  tls:
    - secretName: paperlesspaperless-cert
      hosts:
        - paperless.apps.k8s.vdude.io
        - paperless.vdude.io
  rules:
    - host: paperless.apps.k8s.vdude.io
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: paperless-paperless-ngx
                port:
                  number: 80
    - host: paperless.vdude.io
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: paperless-paperless-ngx
                port:
                  number: 80
