apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  namespace: minecraft-aiden
  labels:
    app: minecraft-server
spec:
  type: LoadBalancer
  ports:
    - name: minecraft-tcp
      port: 25565
      protocol: TCP
      targetPort: 25565
    - name: minecraft-udp
      port: 25565
      protocol: UDP
      targetPort: 25565
  selector:
    app: minecraft-server
