apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml

helmCharts:
  - name: victoria-traces-single
    version: 0.0.5
    releaseName: victoria-traces
    repo: https://victoriametrics.github.io/helm-charts/
    valuesFile: values.yaml
    namespace: tracing
    includeCRDs: true
