apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmCharts:
  - name: valheim-k8s
    version: 2.0.1
    releaseName: valheim-k8s
    repo: https://addyvan.github.io/valheim-k8s/
    valuesFile: values.yaml
    namespace: valheim
