worldName: WolfPack
serverName: RoastyChestnuts
passwordSecret: valheim-password
storage:
  kind: persistentVolumeClaim
  pvc:
    storageClassName: longhorn
    size: 1Gi
serverStorage:
  kind: persistentVolumeClaim
  pvc:
    storageClassName: longhorn
    size: 5Gi
