worldName: WolfPack
serverName: RoastyChestnuts
passwordSecret: valheim-password
extraEnvironmentVars:
  CROSSPLAY: "true"
  SERVER_ARGS: "-modifier resources muchmore -modifier deathpenalty veryeasy -modifier portals casual"
storage:
  kind: persistentVolumeClaim
  pvc:
    storageClassName: longhorn
    size: 10Gi
serverStorage:
  kind: persistentVolumeClaim
  pvc:
    storageClassName: longhorn
    size: 5Gi
