apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - backup-job.yaml

helmCharts:
  - name: longhorn
    version: 1.9.1
    releaseName: longhorn
    repo: https://charts.longhorn.io
    # valuesFile: values.yaml
    namespace: longhorn
