apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argo-cd-app.yaml
  # - authentik-app.yaml
  # - awx-app.yaml
  # - awx-operator-app.yaml
  - cert-manager-app.yaml
  - csi-driver-nfs-app.yaml
  # - external-secrets-app.yaml
  - grafana-alloy-app.yaml
  # - grafana-app.yaml # Omitted on purpose
  - kong-app.yaml
  - kubevip-app.yaml
  - longhorn-app.yaml
  - system-upgrade-controller-app.yaml
  # - kuma-app.yaml
  # - loki-app.yaml
  # - minio-operator-app.yaml
  # - portworx-operator-app.yaml
  # - portworx-app.yaml
  - scrypted-app.yaml
  - sealed-secrets-app.yaml
  # - vault-app.yaml
  # - vault-secrets-operator-app.yaml
  - victoria-k8s-stack-app.yaml
  # - victoriametrics-app.yaml # Omitted on purpose
  - valheim-app.yaml
  - minecraft-aiden-app.yaml
  - victoria-logs-app.yaml
