apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml

helmCharts:
  - name: victoria-logs-single
    version: 0.11.24
    releaseName: victoria-logs
    repo: https://victoriametrics.github.io/helm-charts/
    valuesFile: values.yaml
    namespace: victoria-logs
    includeCRDs: true
  - name: victoria-logs-collector
    # version: 0.2.6
    releaseName: victoria-logs-collector
    repo: https://victoriametrics.github.io/helm-charts/
    valuesFile: collector-values.yaml
    namespace: victoria-logs
    includeCRDs: true
