apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml

helmCharts:
  - name: victoria-logs-single
    # version: 0.11.22
    releaseName: victoria-logs
    repo: https://victoriametrics.github.io/helm-charts/
    valuesFile: values.yaml
    namespace: victoria-logs
    includeCRDs: true
