apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml

helmCharts:
  - name: paperless-ngx
    releaseName: paperless
    repo: https://charts.gabe565.com
    valuesFile: values.yaml
    namespace: paperless
