persistence:
  data:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 1Gi
  media:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 8Gi
  export:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 1Gi
  consume:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 4Gi
postgresql:
  image:
    tag: "latest"
  enabled: true
  primary:
    persistence:
      enabled: true
      storageClass: longhorn
      size: 8Gi
redis:
  image:
    tag: "latest"
  enabled: true
  master:
    persistence:
      enabled: true
      storageClass: longhorn
      size: 2Gi
# ingress:
#   main:
#     enabled: true
#     annotations:
#       cert-manager.io/cluster-issuer: cloudflare-issuer
#     ingressClassName: kong
#     hosts:
#       - host: paperless.apps.k8s.vdude.io
#         paths:
#           - path: /
#       - host: paperless.vdude.io
#         paths:
#           - path: /
#     tls:
#       - secretName: paperlesspaperless-cert
#         hosts:
#           - paperless.apps.k8s.vdude.io
#           - paperless.vdude.io
